spring.datasource.url=jdbc:mysql://localhost:3306/health_app
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

gemini.api.key=${GEMINI_API_KEY}
